import assert from 'node:assert/strict';
import {scheduleVisits} from '../lib/visitSchedule';
import {scheduleVisits as edgeSchedule} from '../../supabase/functions/google-calendar/schedule.js';
const day=new Date('2026-09-21T12:00:00');
const visits=Array.from({length:12},(_,i)=>({id:String(i),cliente_id:String(i),semana:1,dia_semana:'Segunda',ordem_visita:i+1,horario_inicio:'08:00',horario_fim:'09:00'}));
const result=scheduleVisits(visits,[],day);
assert.deepEqual(result.slice(0,11).map(v=>v.horario_inicio),['08:00','08:40','09:20','10:00','10:40','11:20','13:30','14:10','14:50','15:30','16:10']);
assert.equal(result[10].horario_fim,'16:50');assert.equal(result[11].sem_horario,true);assert.equal(result[11].horario_inicio,'');
assert.equal(visits[1].horario_inicio,'08:00');
const sales=(id:string,dates:string[])=>dates.map((d,i)=>({id:id+i,cliente_id:id,faturamento:d,vendas:'VENDAS',tabela:''} as any));
const hist=[...sales('2',['2026-08-01','2026-08-15']),...sales('1',['2026-09-01','2026-09-15'])];
const ordered=scheduleVisits(visits.slice(0,3),hist,day);
assert.deepEqual(ordered.map(v=>v.id),['2','1','0']);
const geo=[{...visits[0],latitude:-26,longitude:-48},{...visits[1],latitude:-27,longitude:-49},{...visits[2],latitude:-26.001,longitude:-48}];
assert.deepEqual(scheduleVisits(geo,[],day).map(v=>v.id),['0','2','1']);
assert.equal(scheduleVisits([{...visits[0],status:'cancelada'}],[],day).length,0);
assert.equal(scheduleVisits([visits[0],{...visits[1],semana:2}],[],day)[1].horario_inicio,'08:00');
assert.deepEqual(edgeSchedule(visits,hist,day),scheduleVisits(visits,hist,day));
console.log('Visit scheduling: slots, lunch, capacity, priority, proximity, cancellation and Edge parity OK');
