export const APP_VERSION = '1.19.2';
export const SALES_CUTOFF_DATE = '2026-04-11';
export const SALES_CUTOFF_CLIENTS = [
  'LUCIA IRIA SCHNEIDER FLORES',
  'EVELYN ADRIANE DE SENNE',
  'ANTONIO DE SOUSA PINHO',
  'SABRINA C PEREIRA DE FARIAS',
  'PEDRO DE FARIAS',
  'VANIA VANESSA DA SILVA M B',
  'AGROMER AGROPECUARIA LTDA',
  'AGROPECUARIA LAPA LTDA',
  'AGROPECUARIA TALISMA LTDA',
  'AGROPECUARIA VEIGA LTDA',
  'AGROPETS LTDA',
  'AGRORICO AGROPECUARIA LTDA',
  'ANTONIO CARLOS BRETAS',
  'CUNHA E CIA LTDA',
  'DANIEL JOSE DALABONA',
  'FAMILIAR AGROPECUARIA LTDA',
  'HUG PET SHOW LTDA',
  'JOICE TATIANE CASAGRANDE',
  'RACAO DE PRIMEIRA LTDA',
  'DOUGLAS FORBICE ME'
];
